### ISSUE TITLE
[bug]: GitHub OAuth2 Error 

### ISSUE THREAD

**Issue by aryasoni98** [xerocodee/InfraBoard#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error : https://cloud.appwrite.io/v1/account/sessions/oauth2/github?success=https%3A%2F%2Fwww.infraboard.xerocodee.com%2F&failure=https%3A%2F%2Fwww.infraboard.xerocodee.com%2Flogin&project=65ca043c0d7319fd7c23

<img width="1214" alt="Screenshot 2024-03-11 at 9 48 21 PM" src="https://github.com/xerocodee/InfraBoard/assets/18515597/1219c96d-78bb-4b17-837f-a19ce2b7ab01">

### Steps to reproduce

GitHub OAuth2 is not working. 

### Environment

Production ( Master Branch )

### Version

Local

### Repository

InfraBoard

**Comment by Divesh-Suryavanshi** [comment]
Since everything seems to be working smoothly in the development environment,  double-check that the redirect URI in your OAuth2 provider's dashboard exactly matches the one displayed in Appwrite's OAuth2 Settings window.

![Screenshot 2024-03-10 141050](https://github.com/xerocodee/InfraBoard/assets/41238260/6e57aaf5-27ba-433e-8228-6b70cdbc532f)
