### ISSUE TITLE
[bug]: Google OAuth2 Error 

### ISSUE THREAD

**Issue by aryasoni98** [xerocodee/InfraBoard#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Error : https://cloud.appwrite.io/v1/account/sessions/oauth2/google?success=https%3A%2F%2Fwww.infraboard.xerocodee.com%2F&failure=https%3A%2F%2Fwww.infraboard.xerocodee.com%2Flogin&project=65ca043c0d7319fd7c23

<img width="1221" alt="Screenshot 2024-03-11 at 9 50 01 PM" src="https://github.com/xerocodee/InfraBoard/assets/18515597/d35f95ca-1d0f-44d3-a7d3-53ee140d8f67">

### Steps to reproduce

Google OAuth2 is not working. 

### Environment

Production ( Master Branch )

### Version

Local

### Repository

InfraBoard

**Comment by Divesh-Suryavanshi** [comment]
Since everything seems to be working smoothly in the development environment,  double-check that the redirect URI in your OAuth2 provider's dashboard exactly matches the one displayed in Appwrite's OAuth2 Settings window.

![Screenshot 2024-03-10 141130(2)](https://github.com/xerocodee/InfraBoard/assets/41238260/6c1b446b-a4a1-4bf3-b8d4-4b1e9a26b7ad)
